### ISSUE TITLE
XC34047

### ISSUE THREAD

**Issue by MichelAntoineReglade** [giletvin/ornidroid#147]
Bonjour. Ce Fichier son est rattaché à 2 espèces roitelet huppé et roitelet triple bandeau. Il s'agit du chant du roitelet TB. Correction possible ? Merci.

**Comment by giletvin** [comment]
Ok. Merci pour l'info. Je corrigerai cela.

**Comment by giletvin** [comment]
fichiers corrigés et envoyés sur FTP
